language: node_js

node_js:
  - 0.10

env:
  global:
    - secure: FaPs4D9IsIvYSbm4fCXG4SIoB3SXzxWl8E5YhCDbd6q4ty++DxsUrTzdinafgbbMVQSqIhsnjeYPvO6h9JQcWh2enor5OPlFvAZqEw0++wsHfOwkYnO9XoS55isO5dZjw9sm705ymrJDRF8rhyfVzuptWGxZLfTynLR0IzWUUFw=

install:
  - npm install
  - npm install -g gulp

script:
  - ./scripts/deploy_docs_to_gh_pages.sh
