language: node_js
node_js:
- 0.1
env:
  global:
  - secure: Gwazk816sjMLOz51QTA9ybdlOMCW8EgGpXqXDF1YNkAiCIQiiecx7WVgQIbBnpD9iV4PDGH7wIhmig0f56WI4a4zVPczZN34X38n+59b1JsaUm4w7+eVwc0MrnkzsN2GAwHsoZPzRtqmi+O0gRaP4m23ky0d8qIiNNVI8HqO86Q=
install:
- npm install
- npm install -g gulp
script:
- "./scripts/deploy_docs_to_gh_pages.sh"
